In [68]:
import torch 
import torch.nn as nn
import torch.nn.functional as F  
import pandas as pd

In [103]:
train = pd.read_csv("train (1).csv")
test = pd.read_csv("test (1).csv")

In [88]:
train.head()

,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,Female,49.0,Ludhiana,Working Professional,Chef,3.142273,5.000000,7.658636,2.94494,2.000000,More than 8 hours,Healthy,BHM,No,1.0,2.0,No
1,Male,26.0,Varanasi,Working Professional,Teacher,3.142273,4.000000,7.658636,2.94494,3.000000,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No
2,Male,33.0,Visakhapatnam,Student,NaN,5.000000,2.998998,8.970000,2.00000,2.974404,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No
3,Male,22.0,Mumbai,Working Professional,Teacher,3.142273,5.000000,7.658636,2.94494,1.000000,Less than 5 hours,Moderate,BBA,Yes,10.0,1.0,Yes
4,Female,30.0,Kanpur,Working Professional,Business Analyst,3.142273,1.000000,7.658636,2.94494,1.000000,5-6 hours,Unhealthy,BBA,Yes,9.0,4.0,Yes

In [71]:
train.drop(columns=['id', 'Name'], inplace=True)
Y = train['Depression']
train.drop(columns=['Depression'], inplace=True)

In [72]:
numerical_feat = train.select_dtypes(include=['number']).columns.tolist()
train[numerical_feat] = train.select_dtypes(include=['number']).apply(lambda col: col.fillna(col.mean()))
numerical_feat

['Age',
 'Academic Pressure',
 'Work Pressure',
 'CGPA',
 'Study Satisfaction',
 'Job Satisfaction',
 'Work/Study Hours',
 'Financial Stress']

In [73]:
categorical_feat = train.select_dtypes(include=['object', 'category']).columns.tolist()
train[categorical_feat].fillna('None')

,Gender,City,Working Professional or Student,Profession,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Family History of Mental Illness
0,Female,Ludhiana,Working Professional,Chef,More than 8 hours,Healthy,BHM,No,No
1,Male,Varanasi,Working Professional,Teacher,Less than 5 hours,Unhealthy,LLB,Yes,No
2,Male,Visakhapatnam,Student,None,5-6 hours,Healthy,B.Pharm,Yes,No
3,Male,Mumbai,Working Professional,Teacher,Less than 5 hours,Moderate,BBA,Yes,Yes
4,Female,Kanpur,Working Professional,Business Analyst,5-6 hours,Unhealthy,BBA,Yes,Yes
...,...,...,...,...,...,...,...,...,...
140695,Female,Ahmedabad,Working Professional,None,5-6 hours,Unhealthy,Class 12,No,Yes
140696,Female,Hyderabad,Working Professional,Content Writer,7-8 hours,Moderate,B.Tech,Yes,Yes
140697,Female,Kolkata,Working Professional,Marketing Manager,More than 8 hours,Moderate,B.Com,No,No
140698,Female,Srinagar,Working Professional,Plumber,5-6 hours,Moderate,ME,Yes,No
140699,Male,Patna,Student,None,Less than 5 hours,Healthy,BCA,Yes,Yes

In [ ]:
test1 = torch.tensor([])
final = torch.cat((test1, torch.tensor([1, 2, 3]).unsqueeze(dim=0)), dim=1)
final

tensor([[1., 2., 3.]])

In [77]:
train['Profession'].values

array(['Chef', 'Teacher', nan, ..., 'Marketing Manager', 'Plumber', nan],
      dtype=object)

In [84]:
column = 'Age'
listt = train[column].values.tolist()
torch.tensor(listt)

tensor([49., 26., 33.,  ..., 24., 49., 27.])

tensor([[1., 2., 3.],
        [1., 2., 3.]])

(140700, 17)

In [ ]:
# Pseudocode: 

"""
count = 0
map = {
"value" : i,
...
}
for row in data:
    for column in row:
        num_classes = self.check_classes(column)
        preset = torch.tensor([])
        if column in numerical_features:
            one_hot = F.one_hot(column, num_classes=num_classes)
            torch.cat(preset, one_hot.unsqueeze(dim=0), dim=1)
        else:
            one_hot F.one_hot(torch.tensor(map[column]), num_classes=len(map.keys()))
            torch.cat(preset, one_hot.unsqueeze(dim=0), dim=1)
    count += 1
    self.data = torch.cat((self.data, preset), dim=0)

return self.data
self.data.shape --> (140700, sum(all_num_classes)))
"""
class Preprocess:
    def __init__(self):
        self.data = torch.tensor([])
    def check_classes(self, column):
        indices = tuple(enumerate(set([i for _, i in enumerate(train[column].values.tolist())])))
        return max(indices)[0] + 1
    def form_input(self):
        for row in train.rows:
            num_classes = self.check_classes(column)
            if column in categorical_feat:
                one_hot_enc = F.one_hot(torch.arange(0, num_classes), num_classes=num_classes)
                self.data = torch.cat((self.data, one_hot_enc.unsqueeze(dim=0)), dim=1)
            else:
                column_values = train[column].values.tolist()
                one_hot_enc = F.one_hot(torch.tensor(column_values), num_classes=num_classes)
                self.data = torch.cat((self.data, one_hot_enc.unsqueeze(dim=0)), dim=1)

        return self.data

preprocesser = Preprocess()
X = preprocesser.form_input()

RuntimeError: one_hot is only applicable to index tensor.